---
# The ACL token to be used to configure and access Consul
# from the Vault cluster.
#
# https://developer.hashicorp.com/vault/docs/configuration/storage/consul
#
# In production, this should be a *new* token, and NOT the master token used for
# the initial bootstrapping of Consul's ACL configuration.
#
# Also note, that this is a sensitive value; an example UUID is provided below
# for demonstration purposes, allowing for consistent/tangible examples
# that can be followed across repositories.

consul_acl_key: "bc2b0299-e39d-43a2-aea8-1a5cc9684ec6"
