---
# The ACL token to be used to configure and access Consul
# from the Vault cluster.
#
# This should be a *new* token, and NOT the master token used for the initial
# bootstrapping of Consul's ACL configuration.
#
# Generate a new token via:
#   NOTE: CONSUL_HTTP_TOKEN should be set outside the command-line, so that
#   it's not visible in your shell history.
#
#   ```
#   export CONSUL_HTTP_TOKEN="bc2b0299-e39d-43a2-aea8-1a5cc9684ec6"
#   # Note: the global-management policy is used here as an example;
#   #       it can be replaced with a policy of more constrained access.
#   consul acl token create -policy-name=global-management
#   ```
consul_acl_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
